// https://env.t3.gg/docs/nextjs#create-your-schema
import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const serverEnv = createEnv({
  server: {
    XAI_API_KEY: z.string().optional().default(''),
    OPENROUTER_API_KEY: z.string().optional().default(''),
    OPENROUTER_MODEL: z.string().optional().default('qwen/qwen3-32b'),
    OPENROUTER_EMBEDDING_MODEL: z.string().optional().default('qwen/qwen3-embedding-8b'),
    OLLAMA_BASE_URL: z.string().optional().default('http://127.0.0.1:11434/v1'),
    OLLAMA_MODEL: z.string().optional().default('qwen3:8b'),
    OPENAI_API_KEY: z.string().optional().default(''),
    ANTHROPIC_API_KEY: z.string().optional().default(''),
    GROQ_API_KEY: z.string().optional().default(''),
    GOOGLE_GENERATIVE_AI_API_KEY: z.string().optional().default(''),
    DAYTONA_API_KEY: z.string().optional().default(''),
    DATABASE_URL: z.string().min(1),
    BETTER_AUTH_SECRET: z.string().min(1),
    GITHUB_CLIENT_ID: z.string().optional().default(''),
    GITHUB_CLIENT_SECRET: z.string().optional().default(''),
    GOOGLE_CLIENT_ID: z.string().optional().default(''),
    GOOGLE_CLIENT_SECRET: z.string().optional().default(''),
    TWITTER_CLIENT_ID: z.string().optional().default(''),
    TWITTER_CLIENT_SECRET: z.string().optional().default(''),
    REDIS_URL: z.string().min(1),
    UPSTASH_REDIS_REST_URL: z.string().min(1),
    UPSTASH_REDIS_REST_TOKEN: z.string().min(1),
    ELEVENLABS_API_KEY: z.string().optional().default(''),
    TAVILY_API_KEY: z.string().optional().default(''),
    EXA_API_KEY: z.string().min(1),
    VALYU_API_KEY: z.string().optional().default(''),
    TMDB_API_KEY: z.string().optional().default(''),
    YT_ENDPOINT: z.string().optional().default(''),
    FIRECRAWL_API_KEY: z.string().optional().default(''),
    PARALLEL_API_KEY: z.string().optional().default(''),
    OPENWEATHER_API_KEY: z.string().optional().default(''),
    GOOGLE_MAPS_API_KEY: z.string().optional().default(''),
    AMADEUS_API_KEY: z.string().optional().default(''),
    AMADEUS_API_SECRET: z.string().optional().default(''),
    CRON_SECRET: z.string().min(1),
    BLOB_READ_WRITE_TOKEN: z.string().min(1),
    SMITHERY_API_KEY: z.string().optional().default(''),
    COINGECKO_API_KEY: z.string().optional().default(''),
    SUPADATA_API_KEY: z.string().optional().default(''),
    QSTASH_TOKEN: z.string().min(1),
    RESEND_API_KEY: z.string().optional().default(''),
    SUPERMEMORY_API_KEY: z.string().optional().default(''),
    SEARXNG_URL: z.string().optional().default('http://192.168.50.158:30053'),
    PLAYWRIGHT_SERVICE_URL: z.string().optional().default('http://127.0.0.1:3001/extract'),
    ALLOWED_ORIGINS: z.string().optional().default('http://localhost:3000'),
  },
  experimental__runtimeEnv: process.env,
});
